import "./globals.css";
import "../../utils/scheduler";
import { Inter } from "next/font/google";
import ReduxProvider from "../redux/Provider";
import { NextAuthProvider } from "./providers";
import { IsClientCtxProvider } from "../lib/is-client-ctx";
import { PurgeProvider } from "../lib/purge";
import Script from "next/script";
import { StrictMode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <IsClientCtxProvider>
          <ReduxProvider>
            <NextAuthProvider>
              <StrictMode>
                <PurgeProvider>{children}</PurgeProvider>
              </StrictMode>
            </NextAuthProvider>
          </ReduxProvider>
        </IsClientCtxProvider>
        <Script src="/scripts/flowbite.min.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
