import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "../redux/Provider";
import { NextAuthProvider } from "./providers";
import { IsClientCtxProvider } from "../lib/is-client-ctx";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NextAuthProvider>
            <IsClientCtxProvider>{children}</IsClientCtxProvider>
          </NextAuthProvider>
        </Providers>
        <Script src="/scripts/flowbite.min.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
